- id: piptools_sync
  name: piptools-sync
  description: Automatically check pre-commit hook versions sync with pip-tools versions
  entry: piptools_sync
  require_serial: true
  language: python
  language_version: python3
  always_run: true
  minimum_pre_commit_version: "2.20.0"
