exclude: |
  (?x)^(
      docs/conf.py|
      docs/example.ipynb|
      tests/[\w]*.py|
      tools/[\w]*.py|
      reports/[\w]*|
      examples/[\w]*.py|
      tasks.py|
      post_installation.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen
        stages: [commit-msg]


  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        args: ["--filter-files"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-eradicate
          - flake8-html
          - Flake8-pyproject
          - flake8-pytest-style
          - flake8-simplify
          - pep8-naming
        args: ["--ignore=E800,F842,F841,W503"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.2.0
    hooks:
      - id: mypy
        alias: mypy
        args:
          [
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --no-warn-unused-ignores,
            --install-types,
            --html-report,
            "reports/mypy",
            --cache-dir,
            "cache/.mypy_cache",
          ]
        additional_dependencies:
          - types-dataclasses
          - lxml
          - types-beautifulsoup4
          - types-html5lib
          - types-python-dateutil
          - types-PyYAML
          - types-requests
          - types-toml
          - types-urllib3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args:
          - -s
          - B101,B301,B403,B404,B603,B607

  - repo: meta
    hooks:
      - id: check-useless-excludes
